### ISSUE TITLE
in-toto conformance tracking issue

### ISSUE THREAD

**Issue by colek42** [testifysec/witness#240]
As part of the donation process to in-toto, we need to ensure that Witness meets the proposed in-toto specification.  This issue is meant to track and discuss the tasks that need to be completed.

- [] Change policy language to match [ITE-10](https://github.com/in-toto/ITE/pull/38)
- [] Switch from an attestation collection to an [attestation bundle](https://github.com/in-toto/attestation/blob/main/spec/bundle.md)
- [] Generate [SLSA](https://slsa.dev/provenance/v0.2) attestation.  Most of the attributes for SLSA are going to be in the CI provider attestation and the command run attestation.

Questions:

- Attestation Collections are verified as a single document.  This has some nice properties, we can assume all of the attestations happened during the same invocation of witness.  How do we bind the attestations in the bundle together?
- We have extended DSSE to support timestamping and embedded cert chains.  How do we do this is we want to bring the DSSE envelope into spec?
