### ISSUE TITLE
CI/CD Process Tracking Issue

### ISSUE THREAD

**Issue by developer-guy** [testifysec/witness#45]
- [ ] create a new release with GoReleaser both for binaries and container images
- [ ] automate workflow with GitHub Actions?
- [ ] sign/verify binaries&container images GitHub Actions OIDC and keyless approach?
- [ ] Mage?
- [ ] golangci-lint?
- [ ] e2e testing?
- [ ] ko?

cc: @colek42 @dentrax @mikhailswift
